version: "3.8"
services:
  backend:
    build: .
    ports:
      - 8080:8080
    links:
      - postgres
    command:
      - /bin/bash
      - -c
      - |
        npx sequelize-cli db:migrate:undo:all
        npx sequelize-cli db:migrate
        npx sequelize-cli db:seed:all
        npm start

  postgres:
    image: postgres:12.4
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

volumes:
  db_data: